### ISSUE TITLE
QueryResponseCommandFacility not installed

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/appfwk#104]
appfwk_QueryResponseCommandFacility_duneCommandFacility has been left out of the call to daq_install; it should be added.

**Comment by alessandrothea** [comment]
Hi John,
Is actually `appfwk_QueryResponseCommandFacility_duneCommandFacility` supposed to be installed?
I would say no, as it is a test program and as such is not meant to be installed.
The same argument applies to all the other modules installed by `CMakeList.txt`, right? `VectorIntFanOutDAQModule_duneDAQModule` `StringFanOutDAQModule_duneDAQModule `NonCopyableTypeFanOutDAQModule_duneDAQModule`

**Comment by jcfreeman2** [comment]
Here are the pro-installation arguments:

* A good heuristic is that code which is in ./src should be installed, code within ./test should not be. appfwk_QueryResponseCommandFacility_duneCommandFacility is build from code in ./src.

* If we use a setup_runtime_environment script which only adds subdirectories of an installation (as opposed to build) area, the instructions in "Compiling and Running" telling new users to run `daq_application -c QueryResponseCommandFacility -j appfwk/test/producer_consumer_dynamic_test.json` will break. Phil's new setup_runtime_environment script does just that.

* Concerning test programs: I think there are two kinds of test programs, integration test programs which developers want to run before cutting a release of their package, and educational test programs which new users of a package can work with to learn how it works, and which typically should be documented in that package's instructions. My sense is that QueryResponseCommandFacility is useful for the latter purpose, as evidenced by its appearance in the "Compiling and Running" instructions, and as such, should be installed.

**Comment by brettviren** [comment]
I suggest making an `examples/` or `demo/` package sub-directory to hold "educational" programs.  I think QRCF deserves to live there.  it would make sense to me to install `.so` and executable build artifacts from `examples/` though possibly via an specific build target (eg `ninja examples`) and possible to a different location than the `.so` from `src/` and execs from `apps/`.

Then, we may require any remaining program in `test/` to either directly run w/out CLI args or provide a script in `test/` that bundles the CLI args needed.  We may then automate `test/` running prior to making releases.

**Comment by alessandrothea** [comment]
Right, answers inline in random order

> * Concerning test programs: I think there are two kinds of test programs, integration test programs which developers want to run before cutting a release of their package, and educational test programs which new users of a package can work with to learn how it works, and which typically should be documented in that package's instructions. My sense is that QueryResponseCommandFacility is useful for the latter purpose, as evidenced by its appearance in the "Compiling and Running" instructions, and as such, should be installed.

Fair enough. From this perspective `appfwk_QueryResponseCommandFacility_duneCommandFacility` is a representative of  the `utilities`/`tools` category. I like Brett's suggestion but at the same time I fear the proliferation of subdirectories.
That said there is a bit of time to play around with directories before we settle on a ~fixed structure.

> * If we use a setup_runtime_environment script which only adds subdirectories of an installation (as opposed to build) area, the instructions in "Compiling and Running" telling new users to run `daq_application -c QueryResponseCommandFacility -j appfwk/test/producer_consumer_dynamic_test.json` will break. Phil's new setup_runtime_environment script does just that.

I need to re-acquaint myself with the development area, and look at Phil's PR, but I would argue against installing everything.
A distinction between build products and installed product is appropriate when it comes to unittests and repo-specific testing programs.
