### ISSUE TITLE
How do I use TRACE

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/appfwk#110]
What do I have to do to fill up my screen with a nice mess of trace messages?  

Maybe something can be added to the wiki?

**Comment by bieryAtFnal** [comment]
Hi Brett,
There is a small section on how to use TRACE in the Step-by-Step instructions for starting out with the _appfwk_.  Please use [this link](https://github.com/DUNE-DAQ/appfwk/wiki/Step-by-step-instructions-for-creating-your-own-DAQModule-package#information-about-the-daqmodules-in-the-listrev-example) and then scroll down to the end of that section (or search for TRACE_FILE in that Wiki page).

I think that your suggestion of a dedicated Wiki page on how to get started with TRACE is a good idea.

In the meantime, here are some simple instructions.  These assume that you want all TRACE messages to go to the console and that you aren't interested (at this time) in making use of the TRACE memory buffer for storing and reading back the TRACE messages.

- start with an existing software area, such as ones described [here](https://github.com/DUNE-DAQ/appfwk/wiki/Compiling-and-running) and [here](https://github.com/DUNE-DAQ/appfwk/wiki/Step-by-step-instructions-for-creating-your-own-DAQModule-package), or one that you created yourself and, in which you have setup TRACE and whatever other dependencies are needed
- `export TRACE_NAME=<path to file which will be used for memory-mapped messages` (e.g. `export TRACE_NAME=${PWD}/log/${USER}_dunedaq.trace`
- `tlvlSg 0xffffffff` (this turns on console messages)
  - the "S" indicates the "slow" path for storing/displaying messages, and the "slow" path corresponds to the console.  The alternative is "M" for memory.
  - the 32-bit hex integer turns on all TRACE levels from 0-31; in fact, there are 64 levels available, so you could use an even longer hex value, if you want
  -  the "g" means "global", which in this case means that this operation should be done for alll TRACE_NAMES [TRACE allows developers to give names to different sections of code to support a nice way to identify the messages from a given class or package]
- run `tlvls`
  - this command displays the currently enabled levels for the Memory, Slow, and Triggered paths.  After running the above tlvlSg command, it should indicate enabled levels 0-31 for the slow ("S") path for all TRACE_NAMES
- run the application (and hopefully see lots of TRACE messages in the console)
- if you want, run `tlvls` again to see the different TRACE_NAMES that were assiccated with the messages

**Comment by brettviren** [comment]
Thanks, @bieryAtFnal  I used GH's search but didn't find this info.  Looks like the wiki search is just on titles.  I do find it now if I go through the full search.

Setting `TRACE_NAME` and running `daq_application` gives me a small file which does seem to have some binary stuff.  So that part seems to be working.

The `tlv*` programs seem not to be available from the Spack build of the appfwk stack but that's not a problem for here.

I'll push forward, thanks!

**Comment by brettviren** [comment]
I'm able to get some action with
```
TRACE_FILE=junk.trace  trace_cntl lvlmskSg 0xffffffff
TRACE_FILE=junk.trace ./build/apps/daq_application --commandFacility file://schema/fdpc-job.json
TRACE_FILE=junk.trace  trace_cntl tids
```
