### ISSUE TITLE
Make it possible to specify the order in which commands are dispatched to modules

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/appfwk#136]
We would like to be able to specify the order in which a command is dispatched to the `DAQModule`s in an application. The motivation here is to be able to ensure clean stop (with all in-flight data handled) in MiniDAQApp v1. In my basic test, a snippet like the one below in the jsonnet file appears to provide the desired command dispatch ordering, but we'd like this to be guaranteed.

```
cmd.stop(
   [
     cmd.mcmd("module1"),
     cmd.mcmd("module2"),
     cmd.mcmd("module3"),
     // etc...
   ]
 ) {}
```

**Comment by glehmannmiotto** [comment]
I’ve been working on this already and have the full stop/start sequence (had to adjust the start).
I’m now following up on some unexpected features.
G
