### ISSUE TITLE
Externally visible running flag

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/appfwk#140]
There are situations in which accessing the running flag via a ThreadHelper handle can be useful. 

Is it possible to have a public getter for this object?

https://github.com/DUNE-DAQ/appfwk/blob/9b5f21a51e25544e07cfd8768b5d46fa91bd882f/include/appfwk/ThreadHelper.hpp#L139

**Comment by mroda88** [comment]
Following the meeting for today, here are more details. In terms of what I'm requesting it is simply a public getter:
```C++
const auto & ThreadHelper::get_running_flag() const { return thread_running_ ; } 
```

It is in general a good idea to have getters, but here is an idea of why we can benefit from this in our operations. 
In the context of having graceful stop transitions, it became clear that having common operations like reading queues, or perform some task, etc wrapped in functions that can be called from inside the running loop and during the draining phase is desirable as these operations are usually very similar if not identical. 
Yet, these operations are usually controlled by the running flag that is passed as an argument to the `do_work` implementation and this flag needs to be propagate as an argument for every one of these wrapping functions, something like
```C++
void MyDAQModule::my_common_operations( std::atomic<bool> & running ) ;
```
If we had the getter in place, we could simplify all these interfaces since the running flag could be obtained from the `ThreadHelper` which is a member of `MyDAQModule`, so the common operation implementation would be:
```C++
void MyDAQModule::my_common_operations( ) {
   // [...]
   while ( m_thread.get_running_flag().load() ) // ...
   // [...]
}
```

**Comment by eflumerf** [comment]
Why is `ThreadHelper::thread_running()` not sufficient?

**Comment by mroda88** [comment]
LOL I completely missed it!
