### ISSUE TITLE
"start" command propagated after "conf" fails

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/appfwk#141]
I'm not entirely sure where the problem is here, but I see the following behaviour with a `daq_application`, which I think could be improved:

1. Send a "conf" command that fails, for whatever reason (an easy way to trigger this is just to modify the conf data in the json file to be invalid somehow, eg by replacing a configuration parameter that should be a scalar with a list)
2. Send a "start" command

In this case, the start command is propagated to all of the modules, including the ones which have not been correctly configured, which typically results in wrong behaviour or a crash. (I run into this problem because I send "init"->"conf"->"start" with a script, rather than reading the output of each command before typing the next). Something should catch the fact that "conf" has failed, and refuse to send out the "start" command.

If we replace "conf"/"start" with "init"/"conf" (with a failing "init"), then the application refuses to propagate the "conf". I think via a check in `DAQModuleManager`.

I guess the general solution to this needs the `daq_application` to be aware of the CCM finite state machine and what the allowed transitions are, which is maybe a bigger discussion. Is there something we can do in the short term to improve this, and make testing easier? Maybe have `DAQModuleManager` know the current FSM state and the list of allowed transitions (by hardcoding)?

**Comment by glehmannmiotto** [comment]
I strongly prefer that we do not put workarounds for this since the work on run control has started and this is part of it.

**Comment by glehmannmiotto** [comment]
fixed
