### ISSUE TITLE
Unit Test harness for DAQModules

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/appfwk#165]
DAQModules are not naturally suited for unit tests, as they have built-in reliance on configuration, queue links, and threads. One potential mitigation for this is to have as much functional code as possible live outside the DAQModule API (i.e. in functions or helper classes), but we also might be able to create a tool that can run certain tests on a DAQModule outside of the runtime (integration test) environment.

**Comment by glehmannmiotto** [comment]
closing this as it doesn't seems to have been followed up
