### ISSUE TITLE
See if some headers can be moved out of public include directory

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/appfwk#171]
Part of finalizing appfwk's official documentation is making sure that the documentation for all public headers is thorough and up-to-date. In the course of looking into this, I've found a couple of headers which may not, in fact, need to be public:
* `include/Logger.hpp`: it seems like this is an artifact of the days before we had the logging package and can be removed from the package entirely
* `include/Application.hpp` and `include/CommandLineInterpreter.hpp`: these both appear to only be `#include`d by `apps/daq_application.cxx`, in which case we should move them into `apps/`

**Comment by jcfreeman2** [comment]
Also `include/DAQModuleManager.hpp`. The only place in our codebase this is included is in `src/DAQModuleManager.cpp` and `include/Application.hpp`, the latter of which is a candidate for removal from the public directory as well.

**Comment by glehmannmiotto** [comment]
We should re-take up this issue @jcfreeman2 and see if really there is a better location for the headers.

**Comment by jcfreeman2** [comment]
@glehmannmiotto Right, I just checked and all my arguments above continue to hold. If you like I can put in a PR where I clean up the public `include/` directory so users of `appfwk` aren't exposed to headers they won't use.

**Comment by glehmannmiotto** [comment]
Thanks John, let's do that.

**Comment by glehmannmiotto** [comment]
While I agree to make the Application and DAQModuleManager headers private, I would have put them into src and not into apps.
