### ISSUE TITLE
Create an intermediate base class which inherits from `DAQModule` but knows about our state machine

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/appfwk#184]
Over the last year, a very common set of idioms have developed which make DAQ module instances controllable via our Run Control state machine. Adding functions like `do_conf`, `do_start`, and `do_work` running an instance of `ThreadHelper`, have become a norm; further discussion can be found in https://dune-daq-sw.readthedocs.io/en/latest/packages/appfwk/ . Writers of DAQ modules meant to be sent run control transitions could be spared having to write these same patterns over and over if we had a class which they could derive directly from and which itself derives from `DAQModule` which has these functions declared and registered, which already has a `ThreadHelper` instance, etc.

**Comment by glehmannmiotto** [comment]
I prefer to not do this, actually. @jcfreeman2 , we should discuss what to do with this issue.

**Comment by jcfreeman2** [comment]
@glehmannmiotto We can drop it; it seems like the trend is for increased flexibility / decreased uniformity of modules (#220). Eric's fine with this as well.
