### ISSUE TITLE
Can we rename "daq_application" instances?

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/appfwk#185]
It might be nice if, instead of a number of "daq_application" instances in `top`, we changed the image name to the name given by the required `--name` parameter.

**Comment by glehmannmiotto** [comment]
we should decide on this issue @eflumerf , and update the PR, if we want this done.

**Comment by eflumerf** [comment]
We have decided that this is not necessary (and may actually interfere with `nanorc` operation)
