### ISSUE TITLE
Move constructors and operator =

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/appfwk#194]
Lines like this one
https://github.com/DUNE-DAQ/appfwk/blob/a258ed46a24840545884dc57bc6ad10299ad3b08/include/appfwk/DAQSink.hpp#L50
 are preventing the usage of sinks and sources in containers, like vectors and maps, unless of course they are are addressed with pointers. 

If we can have those operators implemented instead of deleted, we could avoid the usage of pointers and make the code and the execution smoother. Shall I give it a go with the implementation?

**Comment by glehmannmiotto** [comment]
@mroda88 , I suggest that you bring back up this topic in a core SW meeting and we decide to either do this or close the issue.

**Comment by mroda88** [comment]
@glehmannmiotto I think this will become obsolete anyway with the new Common API, so I will close the issue.
