### ISSUE TITLE
QueueInfo occupancy

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/appfwk#195]
I've been experimenting with dashboards and it's clear that computing on the dashboard the occupancy fraction from number of elements and maximum size, it's not ok if we add thinks like `${partition}` in the query.
Can we add the fraction in the queueinfo as well? I'm happy to prepare the PR.

**Comment by glehmannmiotto** [comment]
Strangely it works for me:
SELECT number_of_elements/capacity FROM "dunedaq.appfwk.queueinfo.Info" WHERE ("source_id" = '${partition}_dataflow.data_fragments_q') GROUP BY "source_id"

**Comment by mroda88** [comment]
Solved, thanks. In my case your command didn't work. What I had to do was adding the quote marks:
```SELECT "number_of_elements" / "capacity" FROM "dunedaq.appfwk.queueinfo.Info" WHERE ("source_id" = '${partition}_dataflow.data_fragments_q') GROUP BY "source_id"
