### ISSUE TITLE
Confusion in separators in unique names

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/appfwk#199]
While developing the dashboards we noticed that the `source_id` names are constructed with the following regular expressions
```
<partition>_<application>.<module>
<partition>_<application>.<card>.<link>   [for felix links]
```
This can possibly create some issues when we want to extract the partition names using regular expressions. 
It would be nice to have a regular naming convention. 

At the moment the difference is happening in appfwk in line
https://github.com/DUNE-DAQ/appfwk/blob/b59752c4816d456da977777ccd22a26558a93e9a/src/Application.cpp#L37 

Chatting with @alessandrothea I understood this was not desirable but also more complicated than simply change the underscore, so this is simply a reminder of the inconsistency.

**Comment by alessandrothea** [comment]
I think we've sorted this out, haven't we?
