### ISSUE TITLE
Rename ThreadHelper class

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/appfwk#205]
The name of the `ThreadHelper` class is rather generic; it doesn't convey the purpose of the class about what it's actually helping out with.
The purpose of this class is supporting the implementation of worker threads in DAQ Modules, i.e. threads the typically execute a repetitive action (loop) that can be interrupted (signature `std::function<void(std::atomic<bool>&)>`).
My suggestion is to rename the class  `WorkerThread` with `start_work` and `stop_work` methods, or something equivalent.

**Comment by eflumerf** [comment]
I'll note that this class was one that we had wanted to move to `utilities`; renaming of the class/methods could happen at the same time as that change.

**Comment by alessandrothea** [comment]
Would make sense. When is that scheduled for?

**Comment by eflumerf** [comment]
I've opened a corresponding issue in `utilities`. I can do it tomorrow; there will definitely have to be updates in other dependencies as well, so it might be useful to have John or Pengfei onboard as well to help.

**Comment by alessandrothea** [comment]
Yes, bring them on board 👍

**Comment by eflumerf** [comment]
The change branches have been merged into the `N22-01-18` nightly
