### ISSUE TITLE
Introduce support for commands (in addition to transition commands)

### ISSUE THREAD

**Issue by glehmannmiotto** [DUNE-DAQ/appfwk#220]

**Comment by glehmannmiotto** [comment]
In order to support additional commands received by the application:
- add an argument to register_command, allowing to indicate the state(s) in which the command can be executed
- limit the per-module-parameters to the INIT/CONF commands only: all other commands will pass the same json object to all modules that registered a method for the command
- revise the schema of command / rc command.

**Comment by plasorak** [comment]
Hi Giovanna, I just want to confirm, we should fix this for 2.11 or 3.0?

**Comment by glehmannmiotto** [comment]
Adding the state in which a command is being executed requires to adjust some test applications in nwqueueadapters and dfmodules, since those tests use execute_command.
