### ISSUE TITLE
have consistent streamer type logging interface (and fast for debugging)

### ISSUE THREAD

**Issue by ron003** [DUNE-DAQ/appfwk#23]
have consistent streamer type logging interface (and fast for debugging)

**Comment by ron003** [comment]
More specifically...
At this point, 6 streamer macros are available and they all begin with "ERS_".
I propose they are changed, to begin with "LOG_" -- which would be more in line with what
should be provided by the include of a header named "Logger.hh"

**Comment by ron003** [comment]
I'll start a separate issue.

**Comment by eflumerf** [comment]
I think with the Logging package, this Issue can be considered complete.
