### ISSUE TITLE
Use a single CMakeLists.txt file

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/appfwk#28]
It's been suggested by Alessandro and others that each package should have a single CMakeLists.txt file, rather than multiple ones spread across multiple subdirectories. Having a single CMakeLists.txt file would not only satisfy this very straightforward requirement but perhaps clarify which CMake wrapper functions might make package developer's lives easier, and which might be unnecessary at best.

**Comment by alessandrothea** [comment]
Hi John, thanks for submitting the PR. A good step forward to simplify the repository organisation.
Now a single file of this size is not easily maintainable, so I was wondering what are your plans to get closer to the ATLAS CMakeLists, e.g.
 
https://github.com/DUNE-DAQ/ers/blob/dune/devel/CMakeLists_old.txt

I think this is what I have in mind for the CMakeList files we want to whip with v1.

**Comment by alessandrothea** [comment]
Can we close this @jcfreeman2 ? It seems to continue in #34

**Comment by jcfreeman2** [comment]
Yes, certainly. This was essentially a prologue to 34.
