### ISSUE TITLE
Review Wiki Pages

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/appfwk#53]
Review wiki pages - delete obsolete pages and check that others are up-to-date

**Comment by eflumerf** [comment]
Ive gone through all of the wiki pages, and I think they are good for now. We will of course keep them updated in response to user questions.

**Comment by mroda88** [comment]
I checked as well most of them. If no other changes are going into the code than the wiki page is in good shape, pending comments or requests from the users that will be addresses once the code is released.
