### ISSUE TITLE
Improve command registration and execution path within DAQModules

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/appfwk#55]
DAQModules should register their command callbacks with DAQProcess. DAQProcess should check if a DAQModule has registered a given command before sending it to the DAQModules.

**Comment by alessandrothea** [comment]
More information needed. Replacing `execute_command` is not really on the table at this stage.

> DAQModules should register their command callbacks with DAQProcess
What do you mean?

> DAQProcess should check if a DAQModule has registered a given command before sending it to the DAQModules.
Indeed.

I assume this is kind of a complementary comment to #44 ?

**Comment by eflumerf** [comment]
I was trying to convert some of the checklist wiki page items into Github issues. Feel free to edit this issue as necessary.

It is intended to be a companion to pull request #44

**Comment by alessandrothea** [comment]
Ha! Got it! No problem!
