### ISSUE TITLE
Finish folly queue implementation

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/appfwk#61]
This requires installing the UPS products for folly and its dependencies to `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products/` after which I will submit a pull request to merge  philiprodrigues:folly-queue-post-rename

**Comment by philiprodrigues** [comment]
The setup script that gets sourced will also have to `setup folly v2020_05_25 -q e19:prof`

**Comment by jcfreeman2** [comment]
I've updated quick-start.sh so as to set up folly, meaning it should be straightforward to test this for the reviewer.

**Comment by philiprodrigues** [comment]
Fixed in PR #62
