### ISSUE TITLE
Remove bool from Queue::pop interface

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/appfwk#73]
`StdDeQueue::pop()` is too noisy, the warning should go

**Comment by jcfreeman2** [comment]
Additionally, the warning takes about 3 ms to execute. And didn't Giovanna say she wanted exceptions thrown on pop timeouts?

**Comment by mroda88** [comment]
Yeah, but we already have the boolean return.

**Comment by bieryAtFnal** [comment]
Yes, my recollection is that we're keeping the boolean return for now, and we'll move to using an exception when we work out how we want to handle T& pop() vs bool pop(T&).

**Comment by glehmannmiotto** [comment]
I did request pop to not return a bool and failures to be marked by an exception. Why is this changing now?

**Comment by bieryAtFnal** [comment]
I've talked with Phil about the right way to change the FollyQueue::pop() method, and I'll be asking for help with StdDeQueue::pop() next.

**Comment by bieryAtFnal** [comment]
Eric, Marco, and John all helped me understand StdDeQueue::pop().  I'm now going to create a biery/Issue73_pop_throws_exception branch, commit changes to that, and get feedback as I go.
