### ISSUE TITLE
Command order not assured in daq_application_constructor 

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/appfwk#97]
This block appears to assume there is an order to JSON objects:

https://github.com/DUNE-DAQ/appfwk/blob/develop/apps/daq_application.cxx#L79

Order is not assured.

https://github.com/nlohmann/json#order-of-object-keys

An array of value objects should be used instead.

It looks like nlohmann gives us lexically sorted keys which in general differs from the as-written JSON text.

```c++
#include "nlohmann/json.hpp"

#include <iostream>

using json = nlohmann::json;

int main()
{
    std::string text = "{\"b\":42, \"a\":2}";
    auto obj = json::parse(text);
    std::cerr << obj << std::endl;
    for (auto& one : obj.items()) {
        std::cerr << one.key() << ":" << one.value() << std::endl;
    }
    return 0;
}
```

output

```
./test_json_order 
{"a":2,"b":42}
a:2
b:42
```

**Comment by alessandrothea** [comment]
Closing, as the code this issue referred to has been overhauled
